const {createClient}=supabase;const db=createClient(window.SUPABASE_URL,window.SUPABASE_KEY);
const fields=["lawyer_name","lawyer_title","address","phone","email","junior_name","junior_phone","customers","cases","experience","consultations","chamber_time","specialization","education","courts","awards","notice","testimonial","faq","facebook","youtube"];
let content=null;
function msg(t,ok=false){const e=document.getElementById("msg");e.textContent=t;e.className=ok?"status success":"status error"}
async function login(){const email=document.getElementById("loginEmail").value.trim(),password=document.getElementById("loginPassword").value;const {error}=await db.auth.signInWithPassword({email,password});if(error){msg(error.message);return}document.getElementById("loginBox").style.display="none";document.getElementById("panel").style.display="block";await load()}
async function load(){const {data,error}=await db.from("site_content").select("*").eq("id",1).single();if(error){msg(error.message);return}content=data;fields.forEach(k=>{const e=document.getElementById(k);if(e)e.value=data[k]??""});await loadGallery()}
async function save(){const update={};fields.forEach(k=>{const e=document.getElementById(k);if(e)update[k]=e.value});update.updated_at=new Date().toISOString();const {error}=await db.from("site_content").update(update).eq("id",1);if(error)msg(error.message);else msg("✓ তথ্য সবার ওয়েবসাইটে সংরক্ষণ হয়েছে।",true)}
async function uploadFiles(){const input=document.getElementById("files");const files=[...input.files];if(!files.length)return msg("আগে ছবি বা ভিডিও নির্বাচন করুন।");const title=document.getElementById("mediaTitle").value.trim();for(const f of files){if(f.size>50*1024*1024){msg("একটি ফাইল ৫০MB-এর বেশি হতে পারবে না।");continue}const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${Date.now()}_${safe}`;const {error:u}=await db.storage.from("gallery").upload(path,f,{contentType:f.type,upsert:false});if(u){msg(u.message);continue}const {data:url}=db.storage.from("gallery").getPublicUrl(path);const type=f.type.startsWith("video/")?"video":"image";const {error:i}=await db.from("gallery").insert({title,file_name:path,file_url:url.publicUrl,file_type:type});if(i)msg(i.message)}input.value="";document.getElementById("mediaTitle").value="";msg("✓ আপলোড সম্পন্ন হয়েছে।",true);await loadGallery()}
async function loadGallery(){const {data,error}=await db.from("gallery").select("*").order("created_at",{ascending:false});if(error){msg(error.message);return}const box=document.getElementById("mediaList");box.innerHTML="";(data||[]).forEach(x=>{const c=document.createElement("div");c.className="media-card";c.innerHTML=(x.file_type==="video"?`<video controls src="${x.file_url}"></video>`:`<img src="${x.file_url}">`)+`<div>${x.title||""}</div><button class="btn danger" onclick="removeMedia(${x.id},'${encodeURIComponent(x.file_name)}')">Delete</button>`;box.appendChild(c)})}
async function removeMedia(id,enc){if(!confirm("এই মিডিয়া মুছে ফেলবেন?"))return;const path=decodeURIComponent(enc);const {error:s}=await db.storage.from("gallery").remove([path]);if(s)return msg(s.message);const {error:d}=await db.from("gallery").delete().eq("id",id);if(d)msg(d.message);else{msg("মুছে ফেলা হয়েছে।",true);await loadGallery()}}
async function logout(){await db.auth.signOut();location.reload()}
window.addEventListener("DOMContentLoaded",async()=>{const {data}=await db.auth.getSession();if(data.session){document.getElementById("loginBox").style.display="none";document.getElementById("panel").style.display="block";await load()}});
