-- LAWYER CHAMBER online database setup
-- 1) Create a Supabase project.
-- 2) Create ONE admin Auth user in Authentication > Users.
-- 3) Replace YOUR_ADMIN_USER_UUID below with that user's UUID and run this SQL.
-- 4) In Storage, create a PUBLIC bucket named: gallery
-- 5) For security, turn off public sign-ups after creating the admin account.

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.site_content (
  id bigint primary key default 1 check (id = 1),
  lawyer_name text default 'শেখ মোহাঃ রফিকুল ইসলাম',
  lawyer_title text default 'আইনজীবী',
  address text default '৪৩ জনসন রোড, ২য় তলা, থানা- সূত্রাপুর, জেলা- ঢাকা',
  phone text default '০১৭১১-৬২০১৬০',
  email text default 'lawerchember@gmail.com',
  junior_name text default 'শাহিনুর ইসলাম',
  junior_phone text default '০১৮৮৯-০৫০০১২',
  customers text default '০০০+',
  cases text default '০০+',
  experience text default '০০+',
  consultations text default '০০+',
  chamber_time text default 'সকাল ১০টা – রাত ৮টা',
  specialization text default 'দেওয়ানি, ফৌজদারি ও অন্যান্য আইনগত বিষয়ে পরামর্শ',
  education text default 'শিক্ষাগত যোগ্যতার তথ্য এখানে লিখুন।',
  courts text default 'আদালত / কর্মক্ষেত্রের তথ্য এখানে লিখুন।',
  awards text default 'অর্জন ও সম্মাননার তথ্য এখানে লিখুন।',
  notice text default 'চেম্বারের গুরুত্বপূর্ণ নোটিশ এখানে লিখুন।',
  testimonial text default 'সম্মানিত গ্রাহকের মতামত এখানে লিখুন।',
  faq text default 'সাধারণ জিজ্ঞাসা ও উত্তর এখানে লিখুন।',
  facebook text default '',
  youtube text default '',
  updated_at timestamptz default now()
);

insert into public.site_content (id) values (1)
on conflict (id) do nothing;

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text default '',
  file_name text not null,
  file_url text not null,
  file_type text not null check (file_type in ('image','video')),
  created_at timestamptz default now()
);

alter table public.admins enable row level security;

-- Allow an authenticated admin to see only their own admin-row; this is needed
-- by the EXISTS checks used by the write policies below.
create policy "admins can read own row"
on public.admins for select
to authenticated
using (user_id = auth.uid());
alter table public.site_content enable row level security;
alter table public.gallery enable row level security;

-- Public website can read content and gallery.
create policy "public can read site content"
on public.site_content for select
to anon, authenticated
using (true);

create policy "public can read gallery"
on public.gallery for select
to anon, authenticated
using (true);

-- Only the admin user listed in public.admins can edit content/gallery.
create policy "admin can update site content"
on public.site_content for update
to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

create policy "admin can insert gallery"
on public.gallery for insert
to authenticated
with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

create policy "admin can delete gallery"
on public.gallery for delete
to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- After creating the admin Auth user with this exact email, run this:
insert into public.admins (user_id)
select id from auth.users where lower(email) = lower('lawerchember@gmail.com')
on conflict (user_id) do nothing;

-- Storage policies for the PUBLIC bucket named gallery.
-- Anyone can view public files; only the listed admin can upload/delete.
create policy "public can view gallery files"
on storage.objects for select
to public
using (bucket_id = 'gallery');

create policy "admin can upload gallery files"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'gallery'
  and exists (select 1 from public.admins a where a.user_id = auth.uid())
);

create policy "admin can delete gallery files"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'gallery'
  and exists (select 1 from public.admins a where a.user_id = auth.uid())
);
